INSERT INTO answer (text) VALUES
('no brothers or sisters'),
('brothers or sisters'),
('any brothers or sisters'),
('some brothers and sisters'),
('a lot'),
('little'),
('too'),
('much'),
('Where playing Real Madrid?'),
('Where is playing Real Madrid?'),
('Where is Real Madrid playing?'),
('Where playing is Real Madrid?'),
('to going'),
('goes to'),
('is going to'),
('go to'),
('on Saturday afternoons'),
('in Saturday afternoons'),
('at Saturday afternoons'),
('by Saturday afternoons'),
('for getting'),
('to getAnswers'),
('to getting '),
('for to getAnswers'),
('wasn\'t nobody'),
('was anybody'),
('was nobody'),
('was somebody'),
('He never comes after 2:30'),
('He never after 2:30 comes'),
('He comes never after 2:30'),
('After 2:30 he never comes'),
('Taking train what you are?'),
('What train taking are you?'),
('Are you what train taking?'),
('What train are you taking?'),
('to leaving'),
('leaves for'),
('is leaving for'),
('leave to'),
('it'),
('him'),
('her'),
('them'),
('Arrives Philip late never.'),
('Late,Philip never arrives'),
('Philip arrives late never.'),
('Philip never arrives late.'),
('Always he wakes up at 9:00.'),
('He wakes up at always 9:00.'),
('He always wakes up at 9:00.'),
('He wakes always up at 9:00.'),
('to going'),
('goes to'),
('is going to'),
('go to');
