INSERT INTO question (id_question, text, id_quiz) VALUES
(1, 'I haven\'t got ……', 1),
(2, 'We haven\'t got ..... Champagne', 1),
(3, '', 1),
(4, 'George..... fly to Stockholm tomorrow.', 1),
(5, 'I have Flamenco classes ……', 1),
(6, 'We have to go to the supermarket ..... some bread and milk.', 1),
(7, 'The party was a disaster. There ..... there!', 1),
(8, '', 1),
(9, '', 1),
(10, 'Michael.........Paris in the morning', 1),
(11, 'That file belongs to Patricia, give it to', 1),
(12, '', 1),
(13, '', 1),
(14, 'Mark ..... fly to London tomorrow.', 1);